replicaCount: 2

namespace: rollouts-argocd

releaseName: rollouts-argocd

image:
  repository: "yadnesh082024/github-actions-backend"
  pullPolicy: IfNotPresent
  tag: main-20241107143047

service:
  type: ClusterIP
  port: 80
  #nodePort: 30040

containers:
  port: 8080

podLabels: {}  # Add this if needed to customize pod labels

ingress:
  enabled: true
  hosts:
    - host: rollouts-argocd.backend-spring-app.com
      paths:
        - path: /spring-app
          pathType: Prefix
